# Generated by Django 3.2.13 on 2022-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_basepage_postpage_videopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='body',
            field=models.TextField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
