# Generated by Django 3.2.13 on 2022-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_videopage_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='tag',
            field=models.CharField(default='add-r', max_length=255),
            preserve_default=False,
        ),
    ]
