# Generated by Django 3.2.13 on 2022-06-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_videopage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='post',
            field=models.TextField(default='post', max_length=100),
            preserve_default=False,
        ),
    ]
