#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py initadmin
/usr/local/bin/gunicorn DemoDocker.wsgi:application --bind 0.0.0.0:8000 --chdir=/app